### ISSUE TITLE
FR14 Implement map layer control

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#29]
- [x] list all layers available in the user's context https://github.com/kartoza/LEDET_BIMS/issues/43
- [x] allow admin to set defaults / save user's settings https://github.com/kartoza/LEDET_BIMS/issues/250
- [x] allow user to change layer order
- [x] allow user to change layer transparency https://github.com/kartoza/LEDET_BIMS/issues/249
- [x] allow user to switch individual layers on and off
- [x] allow user to see layer legend. 
- [x] Layers toggled on should show legend, then user can hide it https://github.com/kartoza/django-bims/issues/221
- [ ] show layers in collapsible tree view (default collapsed), grouped by layer category (get from layer metadata) https://github.com/kartoza/django-bims/issues/118
~~- [ ] allow user to set active layer by clicking on layer name. Then clicking on the map does the equivalent info side panel as for biodiversity (based on GetFeatureInfo, geocontext service etc.). Active = bold font (like biodiversity is now)~~

**Comment by timlinux** [comment]
We still need to figure out where all the base layers will come from and the context layers and which will be available to the current user. If we dust off @ismailsunni 's django-wms and integrate it into k-bims core then @meomancer can add a widget on OL for this. The list shown in OL should be filtered based on user rights.

**Comment by meomancer** [comment]
hi @gubuntu 
about legend toogle, is it like this?
![selection_055](https://user-images.githubusercontent.com/4530905/43577194-620e060c-9675-11e8-98b9-09ba3c11c4d1.png)

it is already implemented (can check "L" button in bottom-left)

**Comment by gubuntu** [comment]
@meomancer I can't test because GeoNode layers are not coming through on testing and staging has lost the original remote list that it had (staging should not have changed at all in the last month,  it is supposed to be stable, coming off master and not have GeoNode yet. cc @dimasciput and @lucernae)

Where are biodiversity and 'administrative' legends?

Does legend toggle on when you toggle a layer on?

**Comment by gubuntu** [comment]
@sonlinux what is there to review? Children of this issue should be done first before this can be reviewed. Please move back into the appropriate column

**Comment by gubuntu** [comment]
done but for #118
