### ISSUE TITLE
FR16 Implement search

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#31]
# Proposed Solution

Add Elastic Search and index 
- [ ] all Biodiversity columns (#248)
- [ ] Class - Need to be able to find different taxonomic groups - e.g. if you search for reptiles or Reptilia, all reptile records should be returned.  (#248)
- [ ] farms and farm portions (#72 ?)
  - by SG code
- [ ] local municipality and district (#211)

**Comment by cchristelis** [comment]
# Proposed Solution

Add Elastic Search and add index Biodiversity columns.

**Comment by gubuntu** [comment]
note NO address search

**Comment by gubuntu** [comment]
from demo Juy 5:
> Farm search must be robust - consider allowing a structured search on SG code component.
